sudo: false
dist: trusty

language: node_js

matrix:
  include:
  - node_js: "6"
  - node_js: "7"
  - node_js: "8"
  - node_js: "9"
  - node_js: "10"

cache:
  directories:
  - node_modules

notifications:
  email: false

script:
 - npm run lint
 - npm run travis
