sudo: false
dist: trusty

language: node_js

matrix:
  include:
    - node_js: "10"
    - node_js: "11"
    - node_js: "12"
    - node_js: "13"
    - node_js: "14"

cache:
  directories:
    - node_modules

notifications:
  email: false

script:
  - npm run lint
  - npm run travis
